version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: it_translator_fastapi
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: it_translator_frontend
    ports:
      - "3001:80"
    depends_on:
      - web
    restart: always
